#!/bin/sh
set -e

INTERVAL="${1:-10}"
DROPIN_DIR="/etc/systemd/system/cap-alert.timer.d"
LEGACY_CRON="/etc/cron.d/cap-alert"

case "$INTERVAL" in
	5|10|15) ;;
	*) INTERVAL=10 ;;
esac

install -d -m 755 "$DROPIN_DIR"
cat >"$DROPIN_DIR/interval.conf" <<EOF
# Generated by cap-alert — change via cap-alert-configure
[Timer]
OnCalendar=*:02/${INTERVAL}
EOF

rm -f "$LEGACY_CRON" "${LEGACY_CRON}.disabled" 2>/dev/null || true

if command -v systemctl >/dev/null 2>&1; then
	systemctl daemon-reload
	if systemctl is-enabled cap-alert.timer >/dev/null 2>&1; then
		systemctl restart cap-alert.timer
	else
		systemctl enable --now cap-alert.timer 2>/dev/null || true
	fi
fi
