#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Merge debconf-generated config with existing manual settings.
 *
 * Usage: merge-debconf-config.php <target-config.php> <generated-config.php>
 */

if ($argc !== 3) {
    fwrite(STDERR, "Usage: merge-debconf-config.php <target> <generated>\n");
    exit(1);
}

$target = $argv[1];
$generatedFile = $argv[2];

if (!is_file($generatedFile)) {
    fwrite(STDERR, "Generated config missing: $generatedFile\n");
    exit(1);
}

$generated = require $generatedFile;
if (!is_array($generated)) {
    fwrite(STDERR, "Generated config must return an array\n");
    exit(1);
}

$existing = [];
if (is_file($target)) {
    $loaded = require $target;
    if (is_array($loaded)) {
        $existing = $loaded;
    }
}

/** Top-level keys owned by the debconf wizard (replaced on reconfigure). */
$wizardKeys = [
    'node', 'lat', 'lon', 'gps', 'tts_key', 'local_playback', 'quiet_hours', 'quiet_hours_window',
    'hold_minutes', 'replay_hours', 'cyclone', 'earthquake', 'wildfire', 'pushover', 'pi', 'filtering',
    'tts_voice', 'asterisk', 'with_county_names', 'playback_window', 'repeat_expanded_on_tail',
    'sounds',
];

$preserved = [];
foreach ($existing as $key => $value) {
    if (!in_array($key, $wizardKeys, true)) {
        $preserved[$key] = $value;
    }
}

if (($generated['tts_key'] ?? '') === '' && ($existing['tts_key'] ?? '') !== '') {
    $generated['tts_key'] = $existing['tts_key'];
}

$existingPushover = is_array($existing['pushover'] ?? null) ? $existing['pushover'] : [];
$generatedPushover = is_array($generated['pushover'] ?? null) ? $generated['pushover'] : [];
if (($generatedPushover['user_key'] ?? '') === '' && ($existingPushover['user_key'] ?? '') !== '') {
    $generatedPushover['user_key'] = $existingPushover['user_key'];
}
if (($generatedPushover['api_token'] ?? '') === '' && ($existingPushover['api_token'] ?? '') !== '') {
    $generatedPushover['api_token'] = $existingPushover['api_token'];
}
$generated['pushover'] = $generatedPushover;

$merged = array_replace_recursive($preserved, $generated);
$export = var_export($merged, true);
$php = <<<PHP
<?php

/**
 * Generated by cap-alert debconf setup.
 * Manual keys outside the wizard are preserved on reconfigure.
 * Edit manually or run: sudo cap-alert-configure
 */
return {$export};

PHP;

file_put_contents($generatedFile, $php);
exit(0);
